version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    # volumes:
    #   - /Home/Documents/code/postgres/mypgdata:/var/lib/postgresql/data
    restart: always
    container_name: my-postgres
    user: root

volumes:
  mypgdata: